#!/usr/bin/env python3
"""Project build tooling. Standard library only, so it runs on a bare interpreter.

    python build.py env lock      resolve the dependencies declared in pyproject.toml and rewrite requirements.txt
    python build.py env rebuild   recreate the ebi-pm environment from requirements.txt

The environment is always recreated from scratch, never edited by hand.
Run it with the base interpreter, not the environment's own (so not via run.sh).
"""
import argparse
import subprocess
import sys
import tomllib
import venv
from pathlib import Path

ROOT = Path(__file__).resolve().parent
VENV = ROOT / "ebi-pm"
REQUIREMENTS = ROOT / "requirements.txt"
HEADER = "# Autogenerated by `python build.py env lock`; do not edit. Source of truth: pyproject.toml\n"


def venv_python() -> Path:
    if sys.platform == "win32":
        return VENV / "Scripts" / "python.exe"
    return VENV / "bin" / "python"


def create_environment() -> Path:
    if Path(sys.prefix).resolve() == VENV.resolve():
        sys.exit("Run this with the base interpreter, not the ebi-pm environment it would delete.")
    venv.EnvBuilder(clear=True, with_pip=True).create(VENV)
    return venv_python()


def pip(python: Path, *args: str, capture: bool = False) -> subprocess.CompletedProcess:
    return subprocess.run(
        [str(python), "-m", "pip", "--disable-pip-version-check", *args],
        check=True,
        text=True,
        capture_output=capture,
    )


def declared_dependencies() -> list[str]:
    with open(ROOT / "pyproject.toml", "rb") as f:
        pyproject = tomllib.load(f)
    return pyproject["project"].get("dependencies", []) + pyproject["build-system"].get("requires", [])


def lock() -> None:
    python = create_environment()
    pip(python, "install", *declared_dependencies())
    REQUIREMENTS.write_text(HEADER + pip(python, "freeze", capture=True).stdout, newline="\n")


def rebuild() -> None:
    if not REQUIREMENTS.exists():
        sys.exit("requirements.txt is missing; run `python build.py env lock` first.")
    python = create_environment()
    pip(python, "install", "-r", str(REQUIREMENTS))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    commands = parser.add_subparsers(dest="command", required=True)
    env = commands.add_parser("env", help="manage the ebi-pm virtual environment")
    env.add_argument("action", choices=["lock", "rebuild"])
    args = parser.parse_args()
    {"lock": lock, "rebuild": rebuild}[args.action]()


if __name__ == "__main__":
    main()
