#!/usr/bin/env python3
"""Project build tooling. Standard library only, so it runs on a bare interpreter.

    python build.py env lock                resolve the dependencies declared in pyproject.toml and rewrite requirements.txt
    python build.py env rebuild             recreate the ebi-pm environment from requirements.txt
    python build.py test [stage ...]        run test stages, logging each to var/test-<step>.log

Test stages (a bare `test` runs rust, bindings and python):
    unit       the hand-written unit tests only; not part of a bare `test`
    generated  the generated blanket tests (tests_autogen); not part of a bare `test`
    functional the slow functional tests (named in FUNCTIONAL_TESTS) and the CLI/integration tests; not part of a bare `test`
    rust       cargo test for the feature sets that CI uses
    bindings   cargo test with the python feature (which includes java)
    python     maturin develop into the ebi-pm environment, then the Python API tests

The environment is always recreated from scratch, never edited by hand.
`env` needs the base interpreter, not the environment's own (so not via run.sh).
`test` needs cargo on the PATH, and the ebi-pm environment for the bindings and python stages.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
import time
import tomllib
import venv
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent
VENV = ROOT / "ebi-pm"
VAR = ROOT / "var"
REQUIREMENTS = ROOT / "requirements.txt"
HEADER = "# Autogenerated by `python build.py env lock`; do not edit. Source of truth: pyproject.toml\n"

# Slow functional tests. They stay in the default `cargo test`; only the unit stage skips them.
FUNCTIONAL_TESTS = [
    "ebi_framework::ebi_output::tests::all_exporters",
    "ebi_framework::ebi_output::tests::ebi_output",
]


def venv_python() -> Path:
    if sys.platform == "win32":
        return VENV / "Scripts" / "python.exe"
    return VENV / "bin" / "python"


def create_environment() -> Path:
    if Path(sys.prefix).resolve() == VENV.resolve():
        sys.exit("Run this with the base interpreter, not the ebi-pm environment it would delete.")
    venv.EnvBuilder(clear=True, with_pip=True).create(VENV)
    return venv_python()


def pip(python: Path, *args: str, capture: bool = False) -> subprocess.CompletedProcess:
    return subprocess.run(
        [str(python), "-m", "pip", "--disable-pip-version-check", *args],
        check=True,
        text=True,
        capture_output=capture,
    )


def declared_dependencies() -> list[str]:
    with open(ROOT / "pyproject.toml", "rb") as f:
        pyproject = tomllib.load(f)
    return pyproject["project"].get("dependencies", []) + pyproject["build-system"].get("requires", [])


def lock() -> None:
    python = create_environment()
    pip(python, "install", *declared_dependencies())
    REQUIREMENTS.write_text(HEADER + pip(python, "freeze", capture=True).stdout, newline="\n")


def rebuild() -> None:
    if not REQUIREMENTS.exists():
        sys.exit("requirements.txt is missing; run `python build.py env lock` first.")
    python = create_environment()
    pip(python, "install", "-r", str(REQUIREMENTS))


@dataclass
class Step:
    label: str
    command: list[str]


def cargo_test(label: str, features: str = "", test_arguments: list[str] | None = None, lib: bool = False) -> Step:
    command = ["cargo", "test", "--locked", "--no-fail-fast"]
    if lib:
        command.append("--lib")
    if features:
        command += ["--features", features]
    if test_arguments:
        command += ["--", *test_arguments]
    return Step(label, command)


def skip(*names: str) -> list[str]:
    return [argument for name in names for argument in ("--skip", name)]


STAGES: dict[str, list[Step]] = {
    "unit": [cargo_test("unit", lib=True, test_arguments=skip("tests_autogen", *FUNCTIONAL_TESTS))],
    "generated": [cargo_test("generated", lib=True, test_arguments=["tests_autogen"])],
    "functional": [
        cargo_test("functional-heavy", lib=True, test_arguments=FUNCTIONAL_TESTS),
        Step("functional-cli", ["cargo", "test", "--locked", "--no-fail-fast", "--test", "prob_trace_cli", "--test", "earth_movers_test"]),
    ],
    "rust": [
        cargo_test("rust-default"),
        cargo_test("rust-exact", "exactarithmetic"),
        cargo_test("rust-approximate", "approximatearithmetic"),
        cargo_test("rust-both", "exactarithmetic,approximatearithmetic"),
    ],
    "bindings": [cargo_test("bindings", "python")],
    "python": [
        Step("python-build", ["maturin", "develop"]),
        Step("python-tests", ["python", "-m", "unittest", "discover", "-s", "tests/python"]),
    ],
}
DEFAULT_STAGES = ["rust", "bindings", "python"]
STAGES_NEEDING_VENV = {"bindings", "python"}


def tool_environment(needs_venv: bool) -> dict[str, str]:
    environment = os.environ.copy()
    if venv_python().exists():
        environment["VIRTUAL_ENV"] = str(VENV)
        environment["PATH"] = str(venv_python().parent) + os.pathsep + environment["PATH"]
        environment["PYO3_PYTHON"] = str(venv_python())
    elif needs_venv:
        sys.exit("The ebi-pm environment is missing; run `python build.py env rebuild` first.")
    return environment


def summarise(log: str) -> tuple[str, list[str]]:
    results = re.findall(r"^test result: \w+\. (\d+) passed; (\d+) failed", log, re.MULTILINE)
    failed_tests = re.findall(r"^test (.+) \.\.\. FAILED$", log, re.MULTILINE)
    if results:
        return f"{sum(int(p) for p, _ in results)} passed, {sum(int(f) for _, f in results)} failed", failed_tests
    ran = re.findall(r"^Ran (\d+) tests?", log, re.MULTILINE)
    if not ran:
        return "see log", []
    problems = re.search(r"^FAILED \((.+)\)$", log, re.MULTILINE)
    failed_tests = re.findall(r"^(?:FAIL|ERROR): (\S+)", log, re.MULTILINE)
    return f"{ran[-1]} Python tests, {problems.group(1) if problems else 'all passed'}", failed_tests


def run_step(step: Step, environment: dict[str, str]) -> bool:
    VAR.mkdir(exist_ok=True)
    log = VAR / f"test-{step.label}.log"
    executable = shutil.which(step.command[0], path=environment["PATH"])
    if executable is None:
        print(f"{step.label}: FAILED, {step.command[0]} is not on the PATH", flush=True)
        return False
    print(f"{step.label}: running {' '.join(step.command)}", flush=True)
    started = time.monotonic()
    with open(log, "w", encoding="utf-8") as out:
        result = subprocess.run(
            [executable, *step.command[1:]], cwd=ROOT, env=environment, stdout=out, stderr=subprocess.STDOUT
        )
    seconds = time.monotonic() - started
    outcome = "ok" if result.returncode == 0 else "FAILED"
    summary, failed_tests = summarise(log.read_text(encoding="utf-8", errors="replace"))
    print(f"{step.label}: {outcome} after {seconds:.0f}s, {summary} ({log.relative_to(ROOT)})", flush=True)
    for name in failed_tests:
        print(f"      FAILED {name}", flush=True)
    return result.returncode == 0


def test(stages: list[str]) -> None:
    stages = stages or DEFAULT_STAGES
    environment = tool_environment(any(stage in STAGES_NEEDING_VENV for stage in stages))
    outcomes = [run_step(step, environment) for stage in stages for step in STAGES[stage]]
    if not all(outcomes):
        sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    commands = parser.add_subparsers(dest="command", required=True)
    env = commands.add_parser("env", help="manage the ebi-pm virtual environment")
    env.add_argument("action", choices=["lock", "rebuild"])
    tests = commands.add_parser("test", help="run test stages")
    tests.add_argument("stages", nargs="*", metavar="stage", help=f"one or more of: {', '.join(STAGES)}")
    args = parser.parse_args()
    if args.command == "env":
        {"lock": lock, "rebuild": rebuild}[args.action]()
    else:
        unknown = [stage for stage in args.stages if stage not in STAGES]
        if unknown:
            parser.error(f"unknown stage(s): {', '.join(unknown)}; choose from {', '.join(STAGES)}")
        test(args.stages)


if __name__ == "__main__":
    main()
